### ISSUE TITLE
long URL workaround

### ISSUE THREAD

**Issue by wareya** [sugoidogo/pngtube2#1]
The custom browser deck thing didn't work for me, but making a local HTML file that redirects to the too-long url, and using that as a file browser source in OBS, *did* work:

```html
<script>
var page = "https://sugoidogo.github.io/pngtube2/v7/overlay.html?<overly long url parameters>"
window.location.href = page;
</script>

```

Just for reference. Thanks for making this!

**Comment by sugoidogo** [comment]
I can't seem to get this to work, could you upload a working example file?

**Comment by sugoidogo** [comment]
Actually, I think I figured out why it's not working for me. Chrome has a hard url limit of 2mb, and my avatar takes up 2.6mb. That limit carries over into OBS, which uses the chrome engine for it's browser source. This workaround is still an improvement from the OBS field limit of 3kb.

**Comment by sugoidogo** [comment]
Thanks for your contribution, I've just made a new release based on this idea that has no size limits whatsoever.
